### PR TITLE
fix: add `ksops install` subcommand for distroless compatibility

### LINKED ISSUE #300: [bug] ArgoCD integration example in README is incorrect (v4.4.0 image no longer contains /bin/sh)
## Bug description

In README.md, we have the following patch example:
https://github.com/viaduct-ai/kustomize-sops?tab=readme-ov-file#ksops-repo-sever-patch
(btw, this patch itself seems to be a bit outdated as well, see #291)

```yaml
# argo-cd-repo-server-ksops-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
        - name: custom-tools
          emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.4.0
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              mv ksops /custom-tools/;
              mv kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
        ## If you use AWS or GCP KMS, don't forget to include the necessary credentials to decrypt the secrets!
        # env:
        #  - name: AWS_ACCESS_KEY_ID
        #    valueFrom:
        #      secretKeyRef:
        #        name: argocd-aws-credentials
        #        key: accesskey
        #  - name: AWS_SECRET_ACCESS_KEY
        #    valueFrom:
        #      secretKeyRef:
        #        name: argocd-aws-credentials
        #        key: secretkey
```

However, starting from v4.4.0, this patch no longer works since the `viaductoss/ksops:v4.4.0` image no longer contains `/bin/sh` nor `cp` binaries, because it builds from `distroless:latest` image.
We get this error in k8s: `failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/bin/sh": stat /bin/sh: no such file or directory`

(This is expected, since [distroless:latest doesn't have shell binaries](https://github.com/GoogleContainerTools/distroless?tab=readme-ov-file#debug-images). If you want one, you are expected to use the `:debug` tag.)

## Proposed solution?

Either include /bin/sh and cp binaries to the image, or rewrite the example to use other containers with sh and cp binaries.

An example of a new patch (replaced initContainers in step 2 and removed `kustomize` volume mount in step 3):
```yaml
# argo-cd-repo-server-ksops-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
        - name: custom-tools
          emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
        - name: install-ksops
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eux
              apk add --no-cache ca-certificates curl tar
              case "$(uname -m)" in
                x86_64|amd64) ARCH="x86_64" ;;
                aarch64|arm64) ARCH="arm64" ;;
                *) echo "unsupported arch: $(uname -m)"; exit 1 ;;
              esac
              VERSION="v4.4.0"
              VERSION_RAW="${VERSION#v}"
              URL="https://github.com/viaduct-ai/kustomize-sops/releases/download/${VERSION}/ksops_${VERSION_RAW}_Linux_${ARCH}.tar.gz"
              curl -fsSL -o ksops.tar.gz "${URL}"
              tar -C /custom-tools -xzf ksops.tar.gz ksops
              chmod +x /custom-tools/ksops
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      # 3. Volume mount the custom binary to the bin directory
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
        ## If you use AWS or GCP KMS, don't forget to include the necessary credentials to decrypt the secrets!
        # env:
        #  - name: AWS_ACCESS_KEY_ID
        #    valueFrom:
        #      secretKeyRef:
        #        name: argocd-aws-credentials
        #        key: accesskey
        #  - name: AWS_SECRET_ACCESS_KEY
        #    valueFrom:
        #      secretKeyRef:
        #        name: argocd-aws-credentials
        #        key: secretkey

```

### PR DESCRIPTION
**Pull request by devstein**
Closes #300

Adding this approach over https://github.com/viaduct-ai/kustomize-sops/pull/303

Add a built-in install subcommand that copies ksops and kustomize
binaries to a target directory, removing the need for /bin/sh and
mv in the Docker image. This fixes the ArgoCD init container
integration broken since v4.4.0 when the image switched to
distroless.

### CODE REVIEW

File: ksops.go [hunk 1]
```diff
@@ -57,14 +58,72 @@ func help() {
...
+		os.Exit(1)
+	}
+
+	dest := args[0]
+
+	binaries := []struct {
+		src  string
+		name string
+	}{
+		{"/usr/local/bin/ksops", "ksops"},
```
Comment (james-callahan) [inline ksops.go:85]: Rather than hardcoding this path would it make sense to use /proc/self/exe as I mentioned in https://github.com/viaduct-ai/kustomize-sops/issues/300#issuecomment-3316644559?

File: ksops.go [hunk 2]
```diff
@@ -57,14 +58,72 @@ func help() {
...
+		{"/usr/local/bin/kustomize", "kustomize"},
```
Comment (james-callahan) [inline ksops.go:86]: I don't think that you need kustomize as part of a normal ArgoCD installation? i.e. this should be opt-in?

**Comment by devstein** [comment]
@james-callahan appreciate the quick review and feedback! This was done with haste. Will push the improvements
